### ISSUE TITLE
[admin] Gérer les contrib où il n'y a pas de générique

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#1108]
- ajouter un flag "nothing" au niveau de la réponse du code du travail OU au niveau de la question
- ajouter un champ pour que le métier puisse mettre le message à afficher quand l'usager sélectionne une CC non traitée / pour laquelle il n'y a pas de réponse

**Comment by romain-b13** [comment]
- [ ] ajouter un bouton radio "Pas de code du travail"
- [ ] champ msg intro
- [ ] champ msg alerte
- [ ] gérer le lien légifrance dans le message

**Comment by maxgfr** [comment]
[ ] Faire une validation coté export pour vérifier qu'on a pas des CCs qui renvoient vers des génériques en NOTHING
