### ISSUE TITLE
Automatiser l'intégration du highlight dans l'admin pour les 77 CC de la méta

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#1116]

**Comment by m-maillot** [comment]
https://github.com/SocialGouv/code-du-travail-numerique/issues/5327

**Comment by m-maillot** [comment]
![Image](https://github.com/SocialGouv/cdtn-admin/assets/992514/6be95d33-d92a-4eeb-8b7b-e27dc736409b)
