### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/cdtn-admin#117]
Add glossary to cdtn-admin
- glossary definition will be handled in a dedicated table
 
 field |  type | info
--- | --- | ---
id | uuid | 
 term | text | markdown
 abbreviations | text  | array with `\n` delimiter  or json
 variants | text | array with `\n` delimiter  or json
 definition | text | markdown
 references | text | array with `\n` delimiter  or json

**Comment by virginielastisneres** [comment]
cette issue a été classée dans done, du coup on peut la clôturer ?

**Comment by UnbearableBear** [comment]
closed with https://github.com/SocialGouv/cdtn-admin/pull/130
