### ISSUE TITLE
[admin] 2 messages différents à mettre pour les contib où il n'y a pas de CDT

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#1212]
Il n'y a qu'un champ pour mettre un message dans la réponse générique mais on a 2 cas de figure différents :
- quand sélection d'une CC non traitée
- quand sélection d'une CC qui ne prévoit rien

[Messages quand générique sans réponse (1).docx](https://github.com/SocialGouv/cdtn-admin/files/13794029/Messages.quand.generique.sans.reponse.1.docx)

**Comment by carolineBda** [comment]
Sortir la liste des contrib qui sont de type CDT ou UNFAVORABLE pour les questions 39, 35, 51 et 48
