### ISSUE TITLE
Pouvoir supprimer/dépublier une convention collective

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/cdtn-admin#1282]
Les conventions collectives évoluent. On identifie 5 cas :

* Création d'une nouvelle convention collective
* Suppression d'une convention collective
* Fusion d'une ou plusieurs conventions collectives dans une autre existante
* Fusion de plusieurs conventions collectives en une nouvelle
* Split d'une convention collective en plusieurs

Dans les 3 derniers cas, il faut prévoir une redirection sur le front. Il y a 2 redirections : la redirection de l'ancienne page de la convention collective vers la nouvelle et le remplacement de l'ancien convention collective par la nouvelle dans la recherche de la CC via l'entreprise (l'api entreprise n'étant pas forcément à jour).

## Création d'une nouvelle convention collective

Cette dernière est géré par les devs en cours

## Suppression d'une convention collective

Il faut ajouter un bouton supprimer sur la page de la convention collective. Ce dernier permet de supprimer la convention collective de la base de données et du site. 

Cas à gérer :
 * La convention collective est référencée par un autre document

## Fusion d'une ou plusieurs conventions collectives dans une autre existante

Il faut permettre à l'utilisation de choisir cette option. Soit via une question supplémentaire après avoir cliqué sur supprimer. Soit via un nouveau bouton merger. Dans ce cas, il faut supprimer la CC de la base de données et du site. Il faut également prévoir une redirection vers la CC cible.

Cas à gérer : 
 * La convention collective est référencée par un autre document

## Fusion de plusieurs conventions collectives en une nouvelle

On peut utiliser le même principe qu'au dessus, il suffit que l'utilisateur crée la nouvelle CC d'abord.

## Split d'une convention collective en plusieurs

Est ce que ce cas existe réellement ? Est ce que l'on veut le gérer car comment on gère la redirection ?

**Comment by m-maillot** [comment]
Tâches :

Frontend admin : 
- [ ] Ajouter une API permettant de supprimer un document. Cette dernière va supprimer le document dans la table concernée et passer le document associé à is_available à `false`. 
- [ ] Ajouter le bouton supprimer sur l'UI appelant cet API
- [ ] Ajouter une bouton merger qui ouvre une modal demandant la CC cible. Une fois la CC choisit, il va créer une entrée dans la table `slug_history` avec le slug de la CC actuel et le cdtnId cible. Puis il va appeler l'API pour supprimer le document. On peut également améliorer l'API de suppression pour passer en paramètre un document cible permettant de d'insérer autmatiquement la ligne dans la table `slug_history`.

Export :
- [ ] Ajouter l'export de la liste des redirections dans un index spécifique. L'index contiendra des documents avec le `slug_source` et le `slug_destination`.

Frontend cdtn :

A étudier: redirections dynamiques et non statiques ou statiques mais que l'on peut regénérer en appelant une API (comme pour la cache).

**Comment by maxgfr** [comment]
Une autre chose concerne le moteur de recherche de convention_collective, où actuellement on définit manuellement les redirections dans [`packages/code-du-travail-frontend/src/api/config.ts`](https://github.com/SocialGouv/code-du-travail-numerique/blob/dev/packages/code-du-travail-frontend/src/api/config.ts)
