### ISSUE TITLE
Migration d'Azure vers S3

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/cdtn-admin#1287]
En prévision de la migration sur OVH, il faut basculer d'azure storage vers le storage S3 d'OVH.

Voici les étapes :

- [ ] Redirection via ngninx des URLs des fichiers pour utiliser notre nom de domaine (exemple :  https://cdtnadmindev.blob.core.windows.net/cdtn/agreements.json vers https://code.travail.gouv.fr/[path]/agreements.json)
- [ ] Dans le base de données, remplacer nos URLs avec la nouvelle URL
- [x] Migrer l'upload des fichiers du frontend sur S3 (bucket en cours de création mais on peut utiliser un docker S3 pour tester en local, exemple : https://github.com/adobe/S3Mock)
- [x] Migrer l'export du sitemap + agreements de l'admin sur S3
- [x] Migrer kali-data pour récupérer les conventions collectives depuis un S3 au lieu d'azure (changement d'une URL)
- [x] Migration du fichier azure vers le S3

**Comment by maxgfr** [comment]
1) Pas besoin de redirection car on build l'URL directement côté frontend
2) Côté BDD, il y a juste les modèles qui sauvegarde l'url en dur, mais on sauvegarde aussi le filename qu'on envoie au frontend, docn pas besoin d'edit
