### ISSUE TITLE
[Admin] Relancer dependabot après la suppression du projet contribution

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/cdtn-admin#1334]

**Comment by maxgfr** [comment]
On fera cette PR une fois que la branche sur l'auth est mergée

**Comment by maxgfr** [comment]
Pour renovate, ça a été relancé suite à l'update 

Pour dependabot, j'ai géré les paramètres ici : https://github.com/SocialGouv/cdtn-admin/settings/security_analysis
