### ISSUE TITLE
[Information] Accordéon dans un accordéon

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/cdtn-admin#1414]
## Description

En tant qu'éditeur
Je souhaite pourvoir créer des accordéons dans des accordéons
Afin de structurer mon contenu

## Critères d'acceptation

 * Etant donné que, j'édite une page info, lorsque je suis dans un accordéon, Alors je peux ajouter un sous accordéon

## Priorité

- [ ] Très haute
- [x] Haute
- [ ] Moyenne
- [ ] Basse
- [ ] Très basse

## Estimation

- [ ] 1
- [ ] 3
- [ ] 5
- [ ] 8
- [ ] 13

**Comment by m-maillot** [comment]
## Proposition

Garder le système de section pour gérer des onglets (mais seulement des onglets). Dans chaque section, on retire la notion de bloc. On bascule sur le composant tiptap avec la possibilité d'ajouter des infographies dans le texte. On a également en dessous de l'éditeur tiptap, la possiblité d'ajouter du contenu lié (comme sur les contributions).

**Comment by carolineBda** [comment]
Peut etre pas prio de suite

**Comment by m-maillot** [comment]
L'idée est de remplacer complètement l'édition actuelle par un tiptap comme sur les contributions.

On effectue une première migration sur les pages infos qui ne sont pas lié à `Comprendre sa procédure de licenciement`. Celles ci utilisant les onglets, il faut voir si on souhaite garder les onglets ou non avant.

Pour les autres pages infos, on va afficher une nouvelle pas d'édition présentant les champs :

 * date de mise à jour
 * titre
 * titre meta
 * description
 * description meta
 * intro

ils sont déjà présents et ne sont pas à modifier.

La partie qui suit sera changée pour être remplacée par un tiptap.

Partie à changer : 

![Image](https://github.com/SocialGouv/cdtn-admin/assets/992514/47abb2a1-a11a-47e2-b20e-7d076ee093b5)


On va utiliser le même tiptap que sur les contributions.

Il y a trois points à valider avant cette modification :

* Comment gérer les infographies ?
* Comment gérer les documents liés ?
* Passage des références en fin de document. Actuellement, on a des références sur chaque bloc.

**Comment by m-maillot** [comment]
Etude sur les infographies : https://github.com/SocialGouv/cdtn-admin/issues/1442

Solution :

 Renommer la rubrique Infographies en Fichiers
 Créer une rubrique Infographies qui va lister l'ensemble des infographies du site.
 Créer une page de création d'une infographie
 Créer une page d'édition d'une infographie
 Créer une page qui liste les infographies
 Créer un script de migration qui prend les infographies des pages informations et les migre dans la nouvelle table des infographies

**Comment by m-maillot** [comment]
Première étape, bouger le contenu en markdown en HTML. 
Il faut basculer les contenus en HTML afin de basculer en tiptap.

L'idée est d'utiliser un script de migration. Le soucis est que l'on ne peut pas faire de markdown to html en SQL.

L'approche serait de générer le HTML en local. Et de créer le script en local pour passer en HTML. Il faut bien se synchroniser avec le métier pour ne pas avoir de modifications pendant ce laps de temps sur les pages infos.

Une fois la migration réalisée, on a les pages infos qui seront compatible avec tiptap.

Voici les étapes :

- [ ] Script de génération du SQL pour migrer du markdown en HTML (à savoir, l'export fait actuellement cette transformation)
- [ ] Utilisation de tiptap dans les pages infos
- [ ] Utilisation du parser tiptap (utiliser sur les contribs) dans les pages infos sur le site

La première étape, peut être remplacée par un job qui va effectuer la migration. Cependant, c'est un code mort qui pourra être supprimé ensuite pour éviter des régressions.
