### ISSUE TITLE
Suppression des APIs

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/cdtn-admin#1415]
Suppression des APIs du frontend (à part celle requises par le client : suggestion et recherche sa CC). 

On effectuera les calls sur ES directement depuis les `getServerProps` de next.js.

**Attention** : le lancement du frontend en local pour le dev ne pourra plus utiliser la preprod comme source de données et va nécessité un ES alimenté pour fonctionner.

**Comment by carolineBda** [comment]
A voir si besoin de re-découper
