### ISSUE TITLE
admin - Interface de gestion des fiches travail-emploi

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/cdtn-admin#144]
Depuis le datafiller, il est possible de spécifier une liste de liens qu'utilisera https://github.com/SocialGouv/fiches-travail-data pour aller récupérer le contenu présent sur https://travail-emploi.gouv.fr/.
Il faudrait que l'admin et https://github.com/SocialGouv/fiches-travail-data soit mis à jour en conséquence pour récupérer cette liste depuis l'admin

**Comment by lionelB** [comment]
Je me demande si il ne faudrait pas se passer de `@socialgouv/fiches-travail-data` et `@socialgouv/fiches-vdd` afin d'éviter de devoir attendre que les version remontent coté admin pour être poussées prod ?

**Comment by UnbearableBear** [comment]
C'est exactement ce à quoi je pensais la dernière fois quand Virignie en a parlé !

**Comment by virginielastisneres** [comment]
@CaptainConan Cette tâche florent sera-t-elle la prochaine des fonctionnalités à mettre en place dans l'admin ? Si oui, est ce qu'il y a des maquettes de la fonctionnalité en cours ? 
mercii :)

**Comment by CaptainConan** [comment]
@virginielastisneres pas de maquette spécifique, dans la mesure où c'est la fonctionnalité présentée par @lionelB en démo ;)

**Comment by lionelB** [comment]
@CaptainConan , je pense que @virginielastisneres faisait référence à l'ajout de nouvelles fiches (et suppression) plutot que la publication / dépublication

**Comment by virginielastisneres** [comment]
> @CaptainConan , je pense que @virginielastisneres faisait référence à l'ajout de nouvelles fiches (et suppression) plutot que la publication / dépublication

oui en effet @CaptainConan à mon sens cette issue est bien différente de la fonctionnalité publication/dépublication qui est déjà mergée. Il s'agit bien ici d'une nouvelle fonctionnalité qui est ajout et suppression de fiches comme l'a dit @lionelB 

:) Il me semblait que c'était la prochaine fonctionnalité prévue sur l'admin non ? (c'est juste pour y voir plus clair dans toutes ces issues :))
