### ISSUE TITLE
Alerting Convention Collective

### ISSUE THREAD

**Issue by carolineBda** [SocialGouv/cdtn-admin#1489]
Alerte du 14/10/2024
la 1626 remonte alors que c'est une ancienne de la méta. 

![Image](https://github.com/user-attachments/assets/834064be-7f2b-4fa6-8455-b7e002dd7f10)

**Comment by m-maillot** [comment]
Le soucis de la 1626, c'est que le fichier DARES la liste (https://travail-emploi.gouv.fr/conventions-collectives-nomenclatures). Etrange que depuis le temps, elle soit encore dans leur fichier. Peut être leur remonter le soucis ?

**Comment by m-maillot** [comment]
Lié à un bug sur le fichier DARES. Corrigé depuis.
