### ISSUE TITLE
administration - Créer un editeur pour les documents de type contenu éditoriaux

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/cdtn-admin#175]
- pouvoir ajouter / supprimer de nouveaux document du type `information`
- pourvoir éditer un document existant
- pouvoir ajouter / supprimer un fichier dans le storage azure

**Comment by UnbearableBear** [comment]
reminder: avoir `filename` (?) et `filesize` dans `document` lors de l'enregistrement

**Comment by UnbearableBear** [comment]
done here https://github.com/SocialGouv/cdtn-admin/pull/204
