### ISSUE TITLE
Bug perte de la session dans l'outil d'admin

### ISSUE THREAD

**Issue by virginielastisneres** [SocialGouv/cdtn-admin#217]
# Description du bug 

Je perds ma session connectée quand je suis dans l'admin et que je recharge la page ou que j'ouvre une page dans un nouvel onglet.

# Reproduction du bug 

1. Se connecter à l'outil d'administration
2. Recharger la page ou ouvrir une page dans un onglet
3. Apparition de la page login

![cdtn admin bug](https://user-images.githubusercontent.com/48682104/101666207-366e7200-3a4e-11eb-87cd-7d2611a4bc7d.gif)

# Comportement attendu 

Une fois connecté à notre session que cette dernière reste sauvegarder le temps que l'on y est et non que ca se déconnecte à chaque action...

**Comment by lionelB** [comment]
closed by #217
