### ISSUE TITLE
Gestion des références dans les dossiers (et eventuellement d'autres contenus ?)

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/cdtn-admin#262]
Idéalement, il faudrait avoir de vraies références entre les contenus (dans les dossiers surtout mais peut-etre que d'autres contenus m'échappent) comme c'est le cas pour les thèmes. Et il faudrait avoir un mécanisme qui liste les listes de références vides en cas de contenus qui ont disparus.

**Comment by lionelB** [comment]
related to https://github.com/SocialGouv/cdtn-admin/issues/141

**Comment by lionelB** [comment]
remplacé par #525
