### ISSUE TITLE
migration des requetes pre-qualified

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/cdtn-admin#272]
Ajouter un / des documents contenant les requetes préqualified
Gestion des prequalified en tant que `document_relation`

**Comment by UnbearableBear** [comment]
Aussi, s'assurer pendant la migration que l'on n'utilise plus:

`getEsReferences` côté cdtn. A priori désormais toutes les références pourront être renseignées complètement en amont lors du "populate" de l'index

**Comment by lionelB** [comment]
closed by #277
