### ISSUE TITLE
migration @cdt/data vers cdtn-admin

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/cdtn-admin#273]
## Objectifs 
Regrouper le code qui manipule la donnée au sein du même projet cdtn-admin. Cela permettra de dé-corréler complètement les job du projet cdtn des données et réduire le travail des pipelines. On limitera ainsi le travail coûteux lié à l'ingestion avec l'utilisation d'alias d'index.

## Pré requis
- utiliser les releases sur cdtn-admin pour permettre de publier et partager des packages sur npm
- déplacer le code de la config ES et du vectorizer et le publier pour pouvoir le ré-utiliser sur cdtn

## travail sur les pipelines
![image](https://user-images.githubusercontent.com/160320/105013797-e7016580-5a3f-11eb-899d-e7d7bbd8fd1e.png)

Le nouveau job de création d'index va créer un nouvel index 
- soit en utilisant un nouvel alias (fourni par le job) sur l'index de prod (ou l'index master) dans le cas d'une release sans mise à jour des données.
- soit en créant un nouvel index ainsi qu'un nouvel alias, dans le cas où l'on doit reconstruire les données.  Le déploiement de l'api et du frontend devront alors attendre que le nouvel index soit accessible (initContainer) avant de pouvoir être accessible.

Il faudra être capable de sauvegarder l'index courant de prod afin de pouvoir lancer des mise à jour depuis l'admin.
Cet information sera mise à jour lors des déploiements qui nécessiteront une synchro cdtn / cdtn-admin (dans le cas où le format des data changent)

Point à valider
- intiContainer synchroniser des container api / frontend
- Test de l'api
- mise à jour des index master et preprod

**Comment by douglasduteil** [comment]
I need to clarify the "breaking change" use case : 


- 🚉 cdtn-admin@master and cdtn.api@master are using alias `cdtn-master`
- New branch feat-x with data update on cdtn-admin@feat-x
  - cdtn-admin@feat-x use alias `cdtn-feat-x`
  - ❓ Manual indexation trigger on cdtn-admin@feat-x of alias `cdtn-feat-x` ?
- New branch feat-x with api/front update on cdtn@feat-x
  - cdtn.api@feat-x use alias `cdtn-feat-x`
  - cdtn.www@feat-x use cdtn.api@feat-x
  - ❓ Manual indexation trigger on cdtn-admin@feat-x of alias `cdtn-feat-x` ?
- Merge of cdtn-admin@feat-x on cdtn-admin@master
  - ❓ Manual indexation trigger on cdtn-admin@master of alias `cdtn-master` ?
  - ⚠️ the alias `cdtn-feat-x` is `cdtn-master`
  - ❓ Is cdtn@master broken ?
- Merge of cdtn@feat-x on cdtn@master
  - 🚉 cdtn@master is using cdtn-admin@master with the feat-x on alias `cdtn-master`
  - ❓ Manual indexation trigger on cdtn-admin@master of alias `cdtn-master` ?
- Release cdtn-admin@B.0.0 !
  - ❓ Is cdtn@A.0.0 broken ?
  - ❓ Manual indexation trigger on cdtn-admin@B.0.0 of alias `cdtn-prod` ?
- Release cdtn@B.0.0 !
  - ❓ Is cdtn@A.0.0 broken ?
  - ❓ Manual indexation trigger on cdtn-admin@A.0.0 of alias `cdtn-prod` ?
- 🚉 cdtn@B.0.0 is using cdtn-admin@B.0.0

**Comment by lionelB** [comment]
[wip] pour completer https://excalidraw.com/#json=6092774562594816,uYmU_JbUgAROF8P18qeRDw

**Comment by douglasduteil** [comment]
[draft https://excalidraw.com/#room=5fff79525e9388af86a4,hhdBsmgibuBpA26mD5yDwg ]

**Comment by douglasduteil** [comment]
I need to clarify the "breaking change" use case : 


- 🚉 cdtn-admin@master and cdtn.api@master are using alias `cdtn-master-v1`
- ❓ Can and should we use the commit sha as index 
  - ⚠️ Over indexing : we should make ensure to index on data change.
- New branch feat-x with data update on cdtn-admin@feat-x
  - 🦶 Change the `ES_INDEX_PREFIX` to `cdtn-feat-x`
  - 🤖 cdtn-admin@feat-x use alias `cdtn-feat-x`
  - 🤖 indexation trigger on cdtn-admin@feat-x of alias `cdtn-feat-x`
  - 🚉 cdtn-admin@feat-x use alias `cdtn-feat-x`
  - ⚠️ Need migrate the ingester to cdtn-admin
- 🦶 New branch feat-x with api/front update on cdtn@feat-x
  - 🦶 Change the `ES_INDEX_PREFIX` to  `cdtn-feat-x`
  - 🚉 cdtn.api@feat-x use alias `cdtn-feat-x`
  - 🚉 cdtn.www@feat-x use cdtn.api@feat-x?
- 🦶 Merge of cdtn-admin@feat-x on cdtn-admin@master
  - 🤖 Detect that `ES_INDEX_PREFIX` is not `cdtn-master-v*`
  - ❓ Is `cdtn-master-vX` versioning automatic ?
  - 🤖 indexation trigger on cdtn-admin@master of alias `cdtn-master-v2`
  - ⚠️ remove the alias `cdtn-feat-x` 
  - 🚉 cdtn-admin@master use alias `cdtn-master-v2`
  - 🚉 cdtn.api@master use alias `cdtn-master-v1`
- 🦶 Api update on cdtn@feat-x
  - 🦶 change `ES_INDEX_PREFIX` to `cdtn-master-v2`
  - ❓ Is `cdtn-master-vX` versioning automatic ?
- 🦶 Merge of cdtn@feat-x on cdtn@master
  - 🚉 cdtn@master is using cdtn-admin@master with the feat-x on alias `cdtn-master-v2`
- 🚉 cdtn-admin@A.0.0 is in production !
  - 🚉 cdtn-admin@A.0.0 use alias `cdtn-prod-vA`
- Release cdtn-admin@B.0.0 !
  - 🤖 indexation trigger on cdtn-admin@B.0.0 of alias `cdtn-prod-vB`
- 🚉 cdtn@A.0.0 is in production !
  - 🚉 cdtn@A.0.0 use alias `cdtn-prod-vA`
- Release cdtn@B.0.0 !
  - 🤖 change `ES_INDEX_PREFIX` to `cdtn-prod-vB`
- 🚉 cdtn@B.0.0 is using cdtn-admin@B.0.0


---

🚉 : station => the state of the system
❓ : question => I'm not sure about this
⚠️ : warning => Might be a problem
🤖 : robot => Automatic action
🦶 : manual => Manual action
