### ISSUE TITLE
Jeux de donnée pour test "end to end" 

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/cdtn-admin#299]
On a besoin d'avoir un environnement reproductible, pour cela, il faudrait qu'on crée un jeu de données avec 
### Alertes

- [ ] alerte code du travail : 1 todo + 1 doing
- [ ] alerte kali : 1 todo + 1 doing (avec des documents lié)
- [ ] alerte fiches-sp (1 todo + 1 doing)
- [ ] alerte fiche-mt (1 todo + 1 doing)
- [ ] 1 commentaire sur une alerte et tester ajout / modif suppression)

### Administration
- [ ] Documents

  - [ ] fiche service-publique
  - [ ] fiche travail-emploi
  - [ ] contribution générique
  - [ ] contribution de cc
  - [ ] convention collective
  - [ ] modèles
  - [ ] outils
  - [ ] outils externes
  - [ ] thème x2
  - [ ] dossier
  - [ ] hightlight
  - [ ] prequalified
  - [ ] contenu editorial
  - [ ] block kali

- [ ] Relations 
  - [ ] theme 1 -> theme 2 (type: theme)
  - [ ] theme 1 -> fiche service-public (theme-content)
  - [ ] hightlight -> document (document-content)

 
- [ ] Fichier (prévoir un bucket de test)

**Comment by douglasduteil** [comment]
<img width=100% src=https://media.giphy.com/media/1T177SywUtbKGJrmqc/giphy.gif />

**Comment by m-maillot** [comment]
On va préférer les tests unitaires aux tests e2e sur l'admin pour le moment. Les tests e2e étant couteux.
