### ISSUE TITLE
Alertes - supprimer le status des articles / section dans les éléments supprimés

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/cdtn-admin#304]
Etant donnée de le fonctionnement de legi-data / kali-data  un article / section peut apparaitre dans la liste des éléments supprimés car il n'est plus présent dans la nouvelle version de l'arbre lorsqu'on compare 2 version d'un texte.
Dans les élément supprimées, nous affichons son ancien etat, ce qui peut induire en  erreur et faire croire qu'un article en vigueur a été supprimé sans être abrogé

**Comment by virginielastisneres** [comment]
Est ce que vous pourriez m'expliquer un peu plus je comprends pas trop ? :)

**Comment by lionelB** [comment]
l'idée c'est de supprimé l'affichage de l'état dans les parties supprimées (car il correspond à l'état avant suppression)
