### ISSUE TITLE
Récupérer les données CDTN depuis la prod dans un environnement de dev

### ISSUE THREAD

**Issue by m-maillot** [SocialGouv/cdtn-admin#320]
# Problème

Lors de l'initialisation d'un environnement de dev, on peut alimenter la base de données avec les données externes (contributions, kali, fiche du travail...). Par contre, il manque des données qui sont éditer par l'équipe CDTN. 

# Solution

Mettre en place une procédure pour récupérer un dump de la prod pour l'avoir en local.

J'ai regardé du coté des API de Hasura, il y a une api pg_dump (https://hasura.io/docs/1.0/graphql/core/api-reference/pgdump.html) mais elle n'est pas encore très au point. Elle ne supporte pas les commandes pour compresser les données par exemple. 
Une autre solution serait de faire un dump directement depuis postgreSQL mais je ne sais pas comment y accéder et si il ne va pas manquer des données dans Hasura.

Il y a surement des autres solutions.

**Comment by lionelB** [comment]
la base est sauvegardée via pg_dump quotidiennement, on devrait pouvoir mettre en place un procédure qui permette d'exposer un dump "nettoyé" des utilisateurs de prod

**Comment by rmelisson** [comment]
https://github.com/SocialGouv/code-du-travail-numerique/issues/3762#issuecomment-940074549

**Comment by carolineBda** [comment]
@m-maillot on va pouvoir close cette issue :)
