### ISSUE TITLE
Optimisation des fichiers

### ISSUE THREAD

**Issue by UnbearableBear** [SocialGouv/cdtn-admin#341]
- Quel types de fichiers souhaitons nous optimiser ?
- Avec quels outils ? Doit-on mettre un service en place pour la fabrique ? Existe-t-il déjà un service en place, payant ?
- A quel moment ? (côté client admin, dans une action, côté client avec next et sa balise <Image>)
- Doit-on mettre en place des gardes fous ? dimension de l’image, poids max etc

**Comment by lionelB** [comment]
coucou @UnbearableBear tu reviens bientôt  ?

**Comment by UnbearableBear** [comment]
Coucou @lionelB ! Haha l’avenir nous le dira :)
