### ISSUE TITLE
[alert] section renomée

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/cdtn-admin#400]
exemple avec la version mise à jour v2.30.0 de kali-data pour la ccn 2216
dans laquelle la section 3 a été renomée
https://github.com/SocialGouv/kali-data/commit/a119e49088af92b519212a129622fbd9ca23e107#diff-e66c1de1d8f74071b68d81ac5710fdb3dcf92fc07165f6b0fd87ab98f2f1fb2aR555

**Comment by virginielastisneres** [comment]
@lionelB peux-tu nous détailler le problème, ses conséquences et la solution proposée stp :) ?

**Comment by lionelB** [comment]
la section renommée apparaît dans les éléments supprimé et dans les éléments ajoutés d'une alerte. il faudrait la passé dans les éléments modifiés
