### ISSUE TITLE
Contenus indisponibles

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/cdtn-admin#442]
Lors de l'ingestion, on utilise un drapeau pour marquer les contenus qui disparaissent lors des mises à jour dans l'idée de pouvoir gérer les 404 ou des redirections coté code-du-travail-numérique.

Il faudrait pouvoir visualiser ces contenus et voir ce que l'on fait avec.

**Comment by romain-b13** [comment]
@lionelB est-ce que cette issue correspond à la volonté de faire apparaître les 404 en alertes dans l'admin ? :)

**Comment by lionelB** [comment]
Non, plutot de montrer que des contenus, qu'on avait sur le site auparavant, ne sont plus disponible maintenant (donc probablement en 404 coté frontend. Un autre soucis qu'on a provient du fait qu'on utilise les titre des documents pour déduire leur url. Si un titre change, l'url va changer et il sera difficile de retracer ce changement (surtout vrai pour les fiches travail et nos contenus)

**Comment by lionelB** [comment]
ces contenus sont visible dans l'admin cf  #488
