### ISSUE TITLE
Problème suppression fiches multiples

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#484]
On pas mal de fiches en double (voir triple, quadruple...) dans les thèmes mais lorsque l'on veut les supprimer, quand il y a une fiche en double, ça supprime les 2, quand la fiche est présente plus de 2 fois on ne peut en supprimer qu'une seule

**Comment by lionelB** [comment]
une ui afin de detecter et faciliter le traitement a été faite ici > c2953c010a273960c9f61c78a87dc316745700e1
committer direct dans master par erreur -_-'

**Comment by romain-b13** [comment]
Je peux clôturer Lionel ?
