### ISSUE TITLE
Remplacer "supprimé" par "disponible"

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#493]
Dans l'exemple ci-dessous ce sont des fiches publiées et bien disponibles, or la cohe dans la colonne "supprimé" laisse penser que ces fiches sont supprimées. Il faudrait simplement remplacer l'intitulé de la colonne "supprimé" par "Disponible"

![image](https://user-images.githubusercontent.com/84397271/123277416-5eaf5100-d506-11eb-91ee-70503d70e56c.png)

**Comment by lionelB** [comment]
closed in #500
