### ISSUE TITLE
Investiguer changement affectation fiches SP

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#507]
Soucis d'affectation de fiches SP :

La source des fiches suivantes est en 404 : 
- https://code.travail.gouv.fr/fiche-service-public/cheque-emploi-associatif-cea
- https://code.travail.gouv.fr/fiche-service-public/animation-quest-ce-que-le-contrat-dengagement-educatif

Pour la fiche cheque emploi associatif CEA, la source n'est plus "https://www.service-public.fr/professionnels-entreprises/vosdroits/F766" mais https://www.service-public.fr/associations/vosdroits/F766

Pour la fiche "animation : qu'est-ce que le contrat d'engagement éducatif", la source n'est plus https://www.service-public.fr/professionnels-entreprises/vosdroits/F23425 mais https://www.service-public.fr/particuliers/vosdroits/F23425

Investiguer pourquoi les nouvelles url (nouvelles affectations) n'ont pas été mises à jour automatiquement

**Comment by lionelB** [comment]
Le probleme vient de l'ingester qui reconstruit mal l'url de la fiches

**Comment by lionelB** [comment]
la page F23425 est dispo aussi dans https://www.service-public.fr/associations  (et remonte dans asso)

**Comment by lionelB** [comment]
close by #523
