### ISSUE TITLE
Analyser fiches non trouvées via le moteur de recherche

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#537]
**Description**
Lorsque l'on essaie de trouver certaines fiches via le moteur de recherche on s'aperçoit que certaines fiches sont introuvables alors que les mots clés semblent pertinents.

Dans l'excel ci-joint on trouve quelques exemples de fiches recherchées (et non trouvées) via le moteur et les requêtes testées.

https://docs.google.com/spreadsheets/d/10Xw05KlnMdLH8yqMtV9TDuMUa_ItiXqR/edit#gid=391000949

**Comment by lionelB** [comment]
closed by #534
