### ISSUE TITLE
modify es token update privilege

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/cdtn-admin#554]
```
action [indices:admin/create] is unauthorized for API key id [key-id] of user [elastic], 
this action is granted by the index privileges [create_index,manage,all]
```

**Comment by revolunet** [comment]
### `create_index`

> Privilege to create an index or data stream. A create index request may contain aliases to be added to the index once created. In that case the request requires the manage privilege as well, on both the index and the aliases names.

why not use the write token that we already have ?
