### ISSUE TITLE
Alertes références juridiques outils/modèles/contenus éditoriaux

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#577]
2 issues sont déjà ouvertes sur ce sujet : 
- https://github.com/SocialGouv/cdtn-admin/issues/587
- https://github.com/SocialGouv/cdtn-admin/issues/141

Aujourd'hui nous n'avons aucun moyen de savoir si une référence juridique sur laquelle nous nous sommes basée pour créer un modèle, un outil ou une page information (contenu propre) a été modifiée.

Résultat attendu : 
Avoir une alerte lorsque qu'une source juridique citée dans un modèle/outil/contenu éditorial est modifiée et pouvoir voir le contenu qui est impacté par cette modification.

**Comment by lionelB** [comment]
page informations
```ts
type InfoReference = {
  type: "Liens utiles" | "Références juridiques"
  links: References[]
}
type References = {
  type: "external"
  id: string
  title: string
  url: string
}
```
dossiers
```ts
type DossierDocument = {
  description: string
  populars: Reference[]
  sections: Section[]
}
type Section = {
  "label": string
  "categories": Category[]
}
type Category = {
  id: string
  icon: string
  title: string
  refs: Reference[]
}
type Reference= {
  title: string
  url: string
}
```
Modèles de document
```ts
type MailTemplate = {
...
references: {
}

**Comment by lionelB** [comment]
Il faut commencer par uniformiser nos références avec au minimun
```
type DilaReference = {
  id:string
  cid: string 
  container_id: string
  // ou 
  type "code_du_travail"  | "conventions_collectives"
  label: string
  url?: string
}
```

**Comment by m-maillot** [comment]
@m-maillot vérifier les contenus supportés

**Comment by m-maillot** [comment]
@romain-b13 
Aujourd'hui, quand on a un changement dans les textes de la dila, on va rechercher les documents associés parmi : 

 * contributions
 * Fiche Ministère du travail
 * Information,
 * Modèles de courrier (dès que l'on aura mis à jour les modèles)
