### ISSUE TITLE
Résoudre échec de la copie des documents preprod -> prod

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#579]
Lors de la dernière MEP le job a échoué mais la MEP est passée et aucune erreur n'était visible du côté de l'admin 
- Voir comment bloquer la MEP lorsque la copie des documents échoue
- Voir comment faire apparaître cet échec de copie sur l'admin

**Comment by lionelB** [comment]
on peut fermer ? (cc @revolunet @m-maillot )

**Comment by m-maillot** [comment]
Il faut que l'on arrive à trouver une solution pour bloquer la MEP quand le processus échoue. Actuellement, on a le processus de l'ingester qui est en amont. Du coup il va mettre à jour les données en prod avant la copie des fichiers. Si ces derniers échouent, la prod sera mise à jour mais pas entièrement. De plus, sur l'admin, on ne voit pas qu'il a échoué et on peut penser que tout est bon.

Il faudrait mettre à jour elastic, copier les fichiers et si pas d'échec éditer l'index d'elastic pour mettre les données visibles en prod.

**Comment by lionelB** [comment]
actuellement la tache se fait coté kube, peut etre qu'il faudrait voir pour la lancer via node  ou sinon il faudrait créer une tache qui ne fasse que l'alias, une fois la copie / maj des donnée effectuée.

**Comment by m-maillot** [comment]
La deuxième solution me semble la plus simple et logique.
