### ISSUE TITLE
Nouvelle version des images non rechargée

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#580]
Lorsque l'on supprime une image dans l'admin (rubrique fichier) et qu'on importe une nouvelle image avec le même nom que celle qui vient d'être supprimée, et qu'on lance une MAJ preprod/prod on aperçoit souvent que c'est toujours l'ancienne image (celle qui a été supprimée) qui est visible en ligne car comme nous gardons le même nom d'image (entre la version supprimée et la version importée) il semblerait que le navigateur pense que c'est la même image et qu'il ne tente donc pas de la recharger.

Voir comment résoudre ce problème ?

Faudrait-il changer de nom lorsque l'on supprime et importe une nouvelle version d'une image ? Si oui, cela peut ensuite être chronophage car il faudra modifier le nom de l'image dans toutes les pages dans lesquelles elle apparaît

**Comment by lionelB** [comment]
@m-maillot on peut fermer ?

**Comment by m-maillot** [comment]
Je pense qu'il faut garder l'issue ouverte. 
Il faut que l'on inclut une clé unique dans le nom de notre coté pour facilité la tâche coté métier. Le palliatif pour le moment étant de modifier le nom à la main pour la métier.

**Comment by m-maillot** [comment]
Voir si on peut modifier les rèlges au niveau de Azure pour forcer la mise à jour par le navigateur des images.

**Comment by m-maillot** [comment]
@revolunet regarde si l'on peut personnaliser la politique de cache de azure storage. La meilleure solution reste de renommer le fichier mais pour pérenniser ce fonctionnement, il faudrait l'automatiser dans l'admin.

**Comment by m-maillot** [comment]
Depuis le mattermost (from @revolunet) :

Par rapport a la question de ce matin relative au cache des assets qui sont sur le container azure storage de cdtn : il n'y a pas de cache par défaut, simplement un header "etag" qui change si le fichier change
ex: https://cdtnadminprod.blob.core.windows.net/cdtn/0-reunion-CSE-juin.png

**Comment by m-maillot** [comment]
La question maintenant est pourquoi l'infographie ne se rafraichit pas toute seule lors d'un changement.

**Comment by m-maillot** [comment]
@romain-b13 pourrait on se planifier un point à se sujet ? L'idée serait de mettre à jour une infographie pour que j'analyse le comportement afin de comprendre pourquoi le navigateur ne va pas chercher cette nouvelle infographie.

**Comment by romain-b13** [comment]
Pas de problème Martial, je te laisse me pinger quand tu as de la dispo pour ça
