### ISSUE TITLE
Page CCN: affichage des blocs CCN 176

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/cdtn-admin#607]
de @CaptainConan 
**Description**
Sur la page de la CC industrie pharmaceutiques (https://preprod-code-du-travail-numerique.dev.fabrique.social.gouv.fr/convention-collective/176-industrie-pharmaceutique), les blocs KALI n'apparaissent pas, alors qu'ils sont bien dans l'admin

![image](https://user-images.githubusercontent.com/37538697/131658988-4518b4c8-acc7-4bcf-a01e-78c3806b3764.png)

**Comment by lionelB** [comment]
Il faut qu'on relance les mise a jour des page CCn lorsque les block kali ou les contrib on changé (en plus des mise a jour kali)
On doit pouvoir utiliser le flag updated_at

**Comment by romain-b13** [comment]
@jrduscher @CaptainConan vous me confirmez que ce souci a été résolu ?

**Comment by jrduscher** [comment]
![image](https://user-images.githubusercontent.com/37538697/142593272-ce84af24-7d40-4b66-ba04-a7b1a7bea6f0.png)
