### ISSUE TITLE
[Admin] Ajouter les thèmes dans les contenus liés d'un contenu en alerte

### ISSUE THREAD

**Issue by CaptainConan** [SocialGouv/cdtn-admin#646]
**Absence des thèmes dans les "contenus liés": alerte fiches MT 4.215 (dans "en cours")**

L'alerte indique la suppression d'une fiche MT. Dans les contenus liés, seule la requête préqualifiée impactée est indiquée. Or, cette fiche se trouvait également dans un thème. Or, la rubrique "Références inaccessibles" remonte bien l'impact de la suppression de la fiche, à la fois sur la requête préqualifiée et sur le thème. 

**Comportement attendu**

Le thème impacté devrait se retrouver dans les "contenus liés" ( à l'instar de la requête préqualifiée).

![CDTN admin ref inaccessibles](https://user-images.githubusercontent.com/53531631/137106631-40dffd01-8b42-45ef-be3e-70b5af884f9f.png)
![CDTN admin alerte Fiches MT 4 215](https://user-images.githubusercontent.com/53531631/137106635-3191188b-27b5-4041-ab90-61d8d1e924ea.png)

**Comment by m-maillot** [comment]
Les thèmes ne sont actuellement pas supportées : 
https://github.com/SocialGouv/cdtn-admin/issues/577#issuecomment-933299755

**Comment by romain-b13** [comment]
> Les thèmes ne sont actuellement pas supportées : [#577 (comment)](https://github.com/SocialGouv/cdtn-admin/issues/577#issuecomment-933299755)

@m-maillot dans la capture d'écran de Florent, du coup ce qu'il y sous le nom de la fiche en gris après "Contenus liés" => ce ne sont que des requêtes préqualifiées dans lesquelles la fiche en alerte apparaît ?

**Comment by m-maillot** [comment]
Oui, c'est bien la requête préqualifiées, on arrive dessus quand on clique sur `conge-paternite`

**Comment by m-maillot** [comment]
En effet, c'est fait à un autre endroit, je ne l'avais pas vu dans le code. Je vais regarder 👀

**Comment by romain-b13** [comment]
@m-maillot peux-tu me confirmer que lorsqu'une fiche SP/MT ou une page information est dépubliée (ou même supprimée pour les fiches MT/SP) celle ci est automatiquement supprimée du thème et de la préqua dans lesquels on trouvait cette fiche ?

Autrement dit l'admnistrateur n'a pas besoin d'aller dans le thème/ la préqua lié à cette fiche pour aller la supprimer des résultats ?
