### ISSUE TITLE
Veille des fiches service public : lien mort dans certaines des alertes

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/cdtn-admin#664]
Dans la veille; une  alerte nous indique qu'une nouvelle fiche a été ajoutée : https://cdtn-admin.fabrique.social.gouv.fr/alerts/socialgouv_fiches-vdd
"Covid-19 : aide au paiement des loyers et charges de certains commerces de détail".
![image](https://user-images.githubusercontent.com/37538697/143059818-ce2684cc-1631-446f-ac2d-3ec3f04296b8.png)

Dans cette alerte, l'url qui pointe vers le contenu sur sp.fr est 404.
Et pour cause: l'url donnée dans l'admin est erronée :https://www.service-public.fr/professionnels/vosdroits/F36039.
 Le lien correct est https://www.service-public.fr/professionnels-entreprises/vosdroits/F36039.

Les effets de ce lien mort semblent limités à l'interface admin après investigation de @m-maillot

**Comment by m-maillot** [comment]
Le lien pour les fiches services publiques est construit dans le code selon le type et le numéro de la fiche. Dans l'ingester, on va correctement construire l'url en indiquant que les fiches de type professionnels possèdent l'URL `https://service-public.fr/professionnels-entreprises/vosdroits/FXXXX`. Tandis que le module alerting va construire l'URL `https://service-public.fr/professionnels/vosdroits/FXXXX`

Il faut mutualiser la fonction permettant de construire les URLs afin d'éviter cette différence de comportement.
