### ISSUE TITLE
Veille des article du code du travail :  Il manque un contenu lié, dans une alerte sur une modification d'article du code du travail

### ISSUE THREAD

**Issue by jrduscher** [SocialGouv/cdtn-admin#666]
### Problème rencontré : 
Un contenu lié à la modification de l'article L1225-62 n'est pas remonté comme contenu lié.
### Description : 

Une modification est intervenue sur l'article L1225-62 du code du travail. Cette modification a été détectée dans le dispositif de veille :
![image](https://user-images.githubusercontent.com/37538697/143256720-53e3ecfc-4c62-48b7-a5b0-3b881daad67a.png)

Le problème se situe au niveau des contenus liés:
Une seule fiche est désignée comme contenu lié.
Il s'avère qu'une autre fiche aurait du remonter comme contenu lié, et ne l'a pas été :
https://code.travail.gouv.fr/fiche-service-public/conge-de-presence-parentale-du-salarie-dans-le-secteur-prive?q=cong%C3%A9%20de%20pr%C3%A9sence%20parentale ( l'article est cité en référence de la fiche)
![image](https://user-images.githubusercontent.com/37538697/143257071-c6b10821-5f70-49cb-972d-e8bd0863bf33.png)

**Comment by m-maillot** [comment]
J'ai trouvé pourquoi la fiche service publique n'est pas remontée, les fiches services publiques ne sont pas encore supportées.

Actuellement, on a:
 * Contrib
 * Fiches ministère du travail
 * Modèles de courrier
 * Contenus éditoriaux

**Comment by m-maillot** [comment]
@romain-b13 
Je pense qu'il faut créer les issues liées pour gérer les références sur les contenus manquants (https://github.com/SocialGouv/cdtn-admin/issues/577#issuecomment-933299755)
