### ISSUE TITLE
[URLs en 404] Ne pas mettre à jour le slug quand il s'agit de la même fiche SP/MT

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#681]
**Description** 
Dernièrement la google search console nous a remonté plusieurs url en erreur par ex celle-ci : https://code.travail.gouv.fr/fiche-service-public/peut-on-entrer-en-apprentissage-apres-la-classe-de-troisieme
Le titre de cette fiche SP a changé "troisième" est devenu "3ème" donc le slug a été mis à jour, ainsi l'ancienne url avec le mot "troisieme" est en 404.

**Problème** 
- Google affiche encore quelque temps l'ancienne URL dans les résultats de recherche
- Les utilisateurs qui aurait partagé l'ancien lien/mis le lien en favori etc. tombe sur la 404

**Contexte**
c'est ici qu'on re-calcul à chaque fois le slug de la fiche :
https://github.com/SocialGouv/cdtn-admin/blob/master/targets/ingester/src/transform/fichesServicePublic/index.ts#L108

donc le slug change si le title change

**Piste de solutions**
- Ne pas mettre à jour le slug quand on sait que c'est la même fiche
- Mettre un place une canonical
- Mettre en place une redirection

**Comment by romain-b13** [comment]
Une issue de 2020 sur ce sujet https://github.com/SocialGouv/code-du-travail-numerique/issues/3058

**Comment by carolineBda** [comment]
Si on part sur ce qui est proposé [ici](https://github.com/SocialGouv/code-du-travail-numerique/issues/3058), il faudra valider la stratégie de migration des urls avec @Jonathan2051

**Comment by carolineBda** [comment]
A part certains lien hardcodés dans le site, le seul moyen d'arriver depuis le site sur une fiche MT/SP c'est via la recherche ?

**Comment by Jonathan2051** [comment]
A mettre à l'ordre du jour du point SEO prévu mercredi 19 à 14h30

**Comment by carolineBda** [comment]
Mettre à jour le sitemap

**Comment by romain-b13** [comment]
Suite au point du 19/01/222 avec Jonathan : 
Pas d'action pour le moment sur les slugs/redirections
D'ici la fin du sprint on voit comment on peut suivre ces 404

**Comment by romain-b13** [comment]
First step : 
Lister combien de personnes voient des 404 sur les fiches MT et SP

**Comment by maxgfr** [comment]
Peut-être, créer une action qui nous parse notre sitemap.xml (cc @revolunet en améliorant ton action, sans passer par un wget mais par /sitemap.xml des sites)

**Comment by maxgfr** [comment]
D'après Sentry, au 26/01/2022, sur les [trente derniers jours](https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/33829/events/?cursor=0%3A0%3A1&environment=production&project=5&query=&statsPeriod=30) nous avons eu :
- **1500** pages non trouvées au total
- **612** issues des [fiches sp](https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/?environment=production&project=5&query=transaction%3A%2Ffiche-service-public%2F%5Bslug%5D&statsPeriod=30d)
- **258** issues des [fiches mt](https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/?environment=production&project=5&query=transaction%3A%2Ffiche-ministere-travail%2F%5Bslug%5D&statsPeriod=30d)

**Comment by carolineBda** [comment]
D'après Matomo, au 28/01/2022, sur les 28 derniers jours nous avons eu :

- **682,608** pages visitées au total
- **82,486** (7.8%) issues des fiches sp : 
- **37,969** (3.6%) issues des fiches mt : 

 -- |Total | SP | MT |
 -- | -- | -- | -- |
 Visites | 682,608 | 82,486 | 37,969 |
 Not found| 1500 | 612 | 258 |
 % Not Found | 0.22% |0,74% |  0,68% |
