### ISSUE TITLE
Pas de différence de niveaux à partir de H3

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#686]
Dans l'admin et dans l'outil de contrib, lorsque l'on utilise les balises Hn pour la rédaction on s'aperçoit qu'à partir de H3 et en dessous la mise en forme est la même (open sans, 18 etc)

US : en tant qu'utilisateur des pages information et des contributions je souhaite pouvoir distinguer facilement le titre d'une section de son sous-titre

**Comment by romain-b13** [comment]
un exemple pour cette page https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/information/indemnite-inflation-infographies?q=inflation

Dans le deuxième accordéon "Qui peut bénéficier de l'indemnité inflation ?" on peut voir que le titre "Quels sont les salariés concernés, quels sont ceux exclus ?" est un H3 et que le titre "Les salariés concernés" est un H5 or ils ont exactement la même mise en forme (18 px, open sans..)

Voici ce que l'on a dans l'admin :
 
![image](https://user-images.githubusercontent.com/84397271/148393223-ed5ef981-41da-4702-a026-ba8a7f3143ca.png)

Voici ce que l'on a en prepord/prod : 

![image](https://user-images.githubusercontent.com/84397271/148393358-38004251-29a8-4bac-9a2f-b3339e6bd84e.png)

**Comment by carolineBda** [comment]
Ici le style est vraiment très facile à changer pour nous :+1: 

Note : il faudrait mettre un h4 au lieu d'un h5 en dessous d'un h3.

**Comment by romain-b13** [comment]
> Ici le style est vraiment très facile à changer pour nous 👍
> 
> Note : il faudrait mettre un h4 au lieu d'un h5 en dessous d'un h3.

Ok super si on peut traité ça rapidement, le souci lorsque l'on rédige depuis l'admin + lorsque l'on rédige depuis l'outil de contrib

**Comment by romain-b13** [comment]
@carolineBda 
Exemple pour un contenu rédigé depuis l'outil de contrib : aller dans l'accordéon "Départ de l’entreprise" puis dans l'accordéon "Quelles sont les conséquences du décès de l’employeur sur le contrat de travail ?" de cette page CC https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/convention-collective/3239-particuliers-employeurs-et-emploi-a-domicile?q=3239

On voit que le 1er titre est en h3 et le deuxième en H4 : 

![image](https://user-images.githubusercontent.com/84397271/148520762-861d9557-2893-430c-980c-6294973a62fe.png)

**Comment by carolineBda** [comment]
> @carolineBda Exemple pour un contenu rédigé depuis l'outil de contrib : aller dans l'accordéon "Départ de l’entreprise" puis dans l'accordéon "Quelles sont les conséquences du décès de l’employeur sur le contrat de travail ?" de cette page CC [code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/convention-collective/3239-particuliers-employeurs-et-emploi-a-domicile?q=3239](https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/convention-collective/3239-particuliers-employeurs-et-emploi-a-domicile?q=3239)
> 
> On voit que le 1er titre est en h3 et le deuxième en H4 :
> 
> ![image](https://user-images.githubusercontent.com/84397271/148520762-861d9557-2893-430c-980c-6294973a62fe.png)
> 
> Du coup c'est pareil si on va sur la page personnalisable en la personnalisant avce la CC 3239 [code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/contribution/quelles-sont-les-consequences-du-deces-de-lemployeur-sur-le-contrat-de-travail](https://code-du-travail-numerique-preprod.dev.fabrique.social.gouv.fr/contribution/quelles-sont-les-consequences-du-deces-de-lemployeur-sur-le-contrat-de-travail)
> 
> ![image](https://user-images.githubusercontent.com/84397271/148521047-6c588298-275e-4a15-84dc-ec290e6dba1e.png)

Ok maintenant ça donne ça
![Screenshot from 2022-01-07 11-41-42](https://user-images.githubusercontent.com/4971715/148532281-58d8fd3b-4f87-4cd8-9c33-ec666e00c931.png)
