### ISSUE TITLE
Ajouter les fiches SP dans les contenus liés des alertes code du travail

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#726]
**Contexte**
Quand un article du code du travail apparaît en alerte, les contenus qui mentionnent cet article en "références juridiques" apparaissent dans "contenus liés" (cf image ci-dessous) : 
![image](https://user-images.githubusercontent.com/84397271/157439676-4487aada-ac8d-4e9b-89a6-fd5601b821ca.png)

Ajourd'hui les contenus qui remontent ici dans les contenus liés sont : 
- Contrib
- Fiches ministère du travail
- Modèles de courrier
- Contenus éditoriaux

**Solution**
Ajouter les fiches SP

Il faudrait également ajouter les simulateurs à posteriori : il faut voir la complexité

**Issues existantes liées :** 
- https://github.com/SocialGouv/cdtn-admin/issues/666
- https://github.com/SocialGouv/cdtn-admin/issues/577
- https://github.com/SocialGouv/cdtn-admin/issues/587
- https://github.com/SocialGouv/cdtn-admin/issues/141

**Comment by m-maillot** [comment]
Pour les simulateurs, il faudrait les intégrer dans l'admin dans un premier temps.

Pour les fiches SP, cela semble être faisable sans trop de difficulté.
