### ISSUE TITLE
Alert script failed: no space left on device

### ISSUE THREAD

**Issue by lionelB** [SocialGouv/cdtn-admin#79]
see https://gitlab.factory.social.gouv.fr/SocialGouv/cdtn-admin/-/jobs/820705

not sure about what we should do.

**Comment by revolunet** [comment]
Try to increase the space here maybe https://github.com/SocialGouv/cdtn-admin/blob/master/targets/alert-cli/.k8s/alert.cronjob.yaml#L68

**Comment by lionelB** [comment]
I initially try to create a bash script to clean the git repository (remove old brench, git gc)

**Comment by lionelB** [comment]
closed by #80
