### ISSUE TITLE
[Admin] Une modification de 4 fiches SP n’est pas remontée en alerte

### ISSUE THREAD

**Issue by CaptainConan** [SocialGouv/cdtn-admin#815]
**Problème :** la suppression d’un lien hypertexte de 4 fiches SP reprises sur le CDTN n’est pas remontée en alerte.
 
Le 01/09/2022, SP a retiré un lien hypertexte des quatre fiches suivantes :

[Accident du travail : démarches à effectuer | Service-public.fr](https://www.service-public.fr/particuliers/vosdroits/F171)  
[Qu'est-ce qu'un accident du travail ? | Service-public.fr](https://www.service-public.fr/particuliers/vosdroits/F178) 
[Qu'est-ce qu'un accident de trajet ? | Service-public.fr](https://www.service-public.fr/particuliers/vosdroits/F31881) 
[Qu'est-ce qu'une maladie professionnelle ? | Service-public.fr](https://www.service-public.fr/particuliers/vosdroits/F31880)

Le lien en bas de page, dans le cartouche “Voir aussi” renvoyait vers un site institutionnel tunisien.
Pour l’exemple, voici ce que cela donnait sur une des fiches SP concernées :
![SP cartouche](https://user-images.githubusercontent.com/53531631/189859970-c1c2fb7c-33ca-4991-8bf6-bc65e482e3ea.png)

Or, la suppression de ce lien hypertexte n’est pas remontée dans les alertes dans l’admin. 
Pour autant, les 4 fiches en question ont bien été mises à jour sans difficulté.

**Comment by m-maillot** [comment]
La partie Voir aussi n'est pas comprise dans la diff. Sur la fiche SP, pour remonter une alerte, on va comparer :
 
 * Introduction
 * Texte (contenu)
 * ListeSituations (qui va correspondre aux questions dans le cas où il y a une situation)
 
Il serait bien de refaire un point sur les attentes à propos de l'alerting ici. Quels sont les parties que l'on souhaite surveiller ? Je peux ajouter la section Voir aussi. Cela semble se faire assez facilement.

**Comment by CaptainConan** [comment]
Oui, on refera un point ensemble.
