### ISSUE TITLE
[Analyse] Mettre en place un alerting lors d'une modif de contenu

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#836]
Commencer à réfléchir **techniquement** sur les différentes possibilités permettant d'afficher l'ensemble des modifs emportées par une MAJ des données sur l'admin au moment du clic sur les boutons "Mettre à jour la pré-production" ou "Mettre à jour la production"

L'objectif d'avoir une vue de l'ensemble des contenus modifiés qui seront emportés par l'action de MAJ : 
- page information
- contribution (générique ou pour une CC en particulier)
- dossier
- Modèles
- Fiches SP
- Fiches MT
- Préqualifiées

Pour donner un exemple concrêt du sujet, on pourrait imaginer un exemple de mise en oeuvre comme celui-ci : 

![image](https://user-images.githubusercontent.com/84397271/196440481-7cb0cfed-513c-40c0-8738-da675f2b081d.png)

**Comment by m-maillot** [comment]
Implémentation de la fonctionnalité:
 
Après discussion, il a été décidé de mettre en place l'architecture CQRS pour gérer les modifications dans les documents et avoir ainsi un suivi dans les modifications apportées en prod.

Voici l'architecture retenue :

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/992514/200542668-f5008a59-3455-4d30-8169-46885d47a856.png">


Exemple concret :

 * L'utilisateur va mettre à jour une page information
 * Le web service va créer une commande UpdateInformationData avec le contenu modifié
 * La commande va être passée à un command handler qui va se charger de valider la commande. Pour cela il va avoir une liste d'aggregate qui chacun est capable de gérer une liste de commande. A la réception de la commande, l'aggregate va valider la commande selon les règles métiers spécifiques à la page information. Il va généré en sortie un event DocumentUpdated.
 * L'event handler va dispatcher les events à des services abonnées (pattern subscriber/publisher). 
 * Le service DocumentUpdateService va recevoir l'event `DocumentUpdated` et va se charger de mettre à jour le document dans la table `documents` puis ajouter une entrée dans la table `pending_documents`.
 
 Le document a été mis à jour :tada: maintenant l'utilisateur souhaite lancer un update des données.
 * L'utilisateur clique sur le bouton mise à jour des données
 * On va afficher la liste des documents présents dans la table `pending_documents` via une query. L'API va transformer la demande en `Query` qui va être traité par un `QueryHandler` qui va utiliser la `Projection`  capable de retourner les données demandées.
  * L'utilisateur valide la mise à jour des données
  * Le web service va créer une command `AskUpdateData` 
  * La commande va être passée au `CommandHandler` qui va utiliser l'aggregate pour valider la demande et générer un event `UpdateDataAsked`. 
  * Un service va se déclencher pour mettre à jour les données. Il va appeler l'API de l'api export pour faire la mise à jour.
  * Lorsque l'API export à fini la mise à jour, il va appeler une API pour indiquer que la MAJ est terminée avec son status.
  * L'API va transformer la demande en commande -> `UpdateDataStatus`
  * La commande est récupérée puis tranformer par un aggregate en `UpdateDataDone` ou `UpdateDataFailed` selon le status de l'update
  * Une projection va écouter l'event `UpdateDataDone` pour mettre à jour la table `pending_documents` en supprimant le contenu mis à jour.

Schéma du débat (un peu brouillon) : 

<img width="1517" alt="image" src="https://user-images.githubusercontent.com/992514/200542852-fa57263d-fccc-4527-af91-539c8414c1dd.png">


On peut implémenter le module CQRS nous même assez facilement. Sinon, on peut également utiliser nest.js avec la lib CQRS (https://docs.nestjs.com/recipes/cqrs). Mais cela demande un projet supplémentaire pour avoir un backend de l'admin, cela en vaut il la peine comme on a déjà Next.js ?

**Comment by m-maillot** [comment]
On peut donc identifier plusieurs étape dans l'implémentation:

 - [ ] Implémentation CQRS `Command`
 - [ ] Passage en commande de la mise à jour d'une page Information
 - [ ] Ajout de la table `pending_documents` avec le service qui écoute l'event de mise à jour de la page info et ajoute une ligne dans la table pour chaque document modifié
 - [ ] Implémentation CQRS `Query` 
 - [ ] Création de l'API permettant d'avoir la liste des documents mis à jour qui va récupérer les données dans la table `pending_documents`
 - [ ] Création de l'API pour valider que la mise à jour des données est terminée (via une commande) qui va supprimer les lignes dans la table `pending_documents` si la MAJ a réussi
 - [ ] Appel de cette API par le service Export ES

On a ainsi une première version avec le support des pages informations (le seul vrai document que l'on peut éditer actuellement). On pourra ainsi ensuite faire la modif pour les autres documents.
