### ISSUE TITLE
[frontend] Basculer le package data dans admin + package cdtn-modeles

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#841]
Basculer le internals.json et externals.json dans l'admin. On bascule les autres json dans cdtn-modeles.

Retirer les informations sur les outils en dur.

Avantage tech :
 * Eviter une desynchro des données
Avantage métier : 
 * Le métier pourra modifier le nom / descriptif / l'action / meta data de l'outil depuis l'admin.

**Comment by romain-b13** [comment]
Voir en même temps l'écart entre les metadescription en prod et celles dans l'admin

**Comment by maxgfr** [comment]
@romain-b13 https://github.com/SocialGouv/code-du-travail-numerique/pull/4741#issuecomment-1325676759
