### ISSUE TITLE
Analyse amélioration de l'outil de contrib

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#871]
### Contexte 

Refonte des pages personnalisables (contributions) afin de fournir une réponse "unique" à l'usager. Le but étant de ne plus avoir une réponse scinder en 2 blocs : ce que prévoit le code du travail et ce que prévoit la CC.

### Attente pour l'utilisateur de l'outil de contrib : 

1- Soit un texte est rédigé dans la réponse de la CC X pour la question X => affichage de ce texte seul

2- Soit la case "la cc ne prévoit rien" est cochée => affichage de la réponse générique

3- Soit la case "désolé nous n'avons pas de réponse" est cochée => affichage de la réponse générique + afficher le texte "pas de réponse pour cette question pour cette CC" (comme quand la CC sélectionnée n'est pas traitée sur le CDTN)

4- Choix du message générique (articulation des sources) à afficher (bloc1, bloc 2, bloc 3...)

5- Pouvoir associer les contenus liés (liens vers d'autres contenus)

- au niveau de la réponse de la CC (si pas de réponse de la CC => on affiche les liens du niveau générique)
- au niveau de la réponse générique

6- Pourvoir associer des références juridiques à chaque réponse (générique ou CC)

### Besoins métier :

**1. Pouvoir modifier des réponses pour préparer la refonte sans impacter les réponses en prod**
- 2 outils de contrib en parallèle ?

**2. Pouvoir afficher 1 seule réponse sur le front :** 

- La réponse de la CC (partielles et totales) : si l'utilisateur sélectionne sa CC + qu'elle est traitée sur le CDTN + qu'elle prévoit quelque chose pour cette question (L'usager qui recherche "congé mariage banque" sur Google doit donc arrivé directement sur la réponse de la CC de la Banque sans action de sélection de CC)

- La réponse du code du travail : 
        - Lorsque la CC ne "prévoit rien" pour cette question
        - Lorsque la CC sélectionnée par l'usager n'est pas traitée par le CDTN
        - Lorsque l'usager ne souhaite pas sélectionner de CC
        - Lorsque la réponse pour cette CC n'est pas traitée

**3. Pouvoir afficher des messages "génériques"**

- Quelque que soit la réponse affichée : il faudra afficher un message qui explique qu'un accord d'entreprise, le contrat de travail, usage, accord non étendu etc. peut prévoir une autre réponse

- Lorsque la CC sélectionnée par l'usager n'est pas traitée par le CDTN **OU** que l'usager ne sélectionne pas de CC : il faudra ajouter dans le message générique la notion de convention collective (puisque l'usager aura eu la réponse du code du travail)

**4. Pouvoir afficher des liens vers des contenus (articles, outils, modèles...) pour aller plus loin (à voir)**

**5. Comme actuellement, pouvoir afficher les réf juridiques de la réponse affichée**

**6. SEO**
- cela pose-t-il problème d'avoir des pages sans contenu tant que l'usager n'a pas sélectionné de CC ? 
- l'usager doit toujours pouvoir accéder direct à la réponse de sa Cc (sans aucune action à faire) depuis Google, lorsqu'il fait une requête du type "congés mariage automobile"

**7. Pages CC** 

- Avoir le message qui explique qu'une autre réponse peut s'appliquer (un accord d'entreprise, le contrat de travail etc..)
- Si la CC ne prévoit rien pour une question, actuellement cette question n'est pas affichée dans la page CC, du coup est-ce que pour ce cas on décide d'afficher la question avec la réponse du code du travail ?
- Si la CC n'offre qu'une réponse partielle pour une question, dans la page CC on affichera pour cette question le mix réponse de la CC + du réponse du CDT ?
- Retirer ce message automatique présent sur toutes les réponses dans les pages CC : 

![image](https://user-images.githubusercontent.com/84397271/217577734-0c8981bb-3b28-45d7-baa1-f4a0f387eab4.png)

**Comment by romain-b13** [comment]
Cette fonctionnalité "réponse proposée" ne sert pas : 

![image](https://user-images.githubusercontent.com/84397271/227262169-033e24c9-f49f-43d2-9d72-0693624c9750.png)

**Comment by m-maillot** [comment]
Point à demander:

## Conventions collectives 

 * Faut il garder la notion de CC parente ?
 * Faut il des filtres multi select ?
 * Est ce que l'on garde la sauvegarde automatique ?
 * Est ce que l'on garde les étapes de validation ?
 * Qu'est ce que le renvoie ?

Etapes :
 * Intégrer cdtn-api dans l'admin.
 * Lister les fonctionnalités et valider avec le métier si on garde, on modifie ou on jette.
 * Ajouter une section contrib dans l'admin
  -> Dupliquer les tables contribs afin de garder l'ancien outil fonctionnel /!\ Eviter la désynchro /!\ -> A voir avec le métier (si modifs dans les contribs, comment les syunchroniser avec les nouvelles données si besoin)
   -> Créer les fonctionnalités de base à définir
   -> Supprimer l'ingestion des contribs dans l'admin et modifier l'export des données pour générer 
  
Sujet à part entière qui n'est pas lié au dev de l'outil de contrib

 * Pouvoir associer les contenus liés (liens vers d'autres contenus)


A voir avec @romain-b13 
 * Pourvoir associer des références juridiques à chaque réponse (générique ou CC)

**Comment by romain-b13** [comment]
Quelques éléments supplémentaires soumis par le métier sur des améliorations de l'outil (pas uniquement lié à la refonte des pages personnalisables) :

- Pouvoir modifier une réponse sans dépublier celle qui est en prod (faire coexister 2 versions ?) : une sorte d'espace de travail qui n'impacte pas la réponse qui est en prod tant que la modification n'est pas finalisée
- Lier une modification à la personne qui l'a faite et envoyer une alerte au valideur pour validation de la modif
- Faire repasser la réponse modifiée par tous les statuts
- L'encadré "réponse proposée" n'est pas utile mais pourrait l'être lorsqu'une réponse est dans le statut "en cours de validation"
- Pour les réponses génériques il manque la recherche comme pour les réponses des CC 
- Markdown : avoir quelque chose comme : 

![image](https://user-images.githubusercontent.com/84397271/229568015-17220c47-1139-4430-af38-2e34912abdc9.png)

Questions :
- Si on supprime une question ou une CC ça supprime automatiquement toutes les réponses liées ?
- Si on créé une question ou une CC ça génére autoamtiquement toutes les réponses liées ?

A supprimer :
Les unités
