### ISSUE TITLE
[Outil de contrib] Picto ref juridique obsolète ne fonctionne pas

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#886]
- voir le fonctionnement
- si ne fonctionne pas : voir avec le métier le besoin et si la correction peut attendre la refacto de l'outil

**Comment by m-maillot** [comment]
Cas remonté par Florent:
> Par exemple, IDCC 176, contribution 10) Quelles sont les conditions de la clause de non-concurrence ? , l'article 31.3 b est indiqué KO (le lien est KO), alors que l'article est bien en vigueur.

Analyse:

Voici ce que les données de Kali me donne :
On a le KALIARTI000005857730 qui contenait l'article 31 en VIGUEUR_ETEN et le KALIARTI000039117098 en VIGUEUR_NON_ETEN jusqu'au 14/07/2021. A partir de cette date, le KALIARTI000005857730 est supprimé et le KALIARTI000039117098 est passé à VIGUEUR_ETEN.
D'ailleurs sur https://www.legifrance.gouv.fr/conv_coll/article/KALIARTI000039117098, on voit que l'article a été étendu le 2 avril 2021

![image](https://user-images.githubusercontent.com/992514/225065159-51d73466-8567-41fa-ad0a-703537edebb2.png)

**Comment by m-maillot** [comment]
En attente du soucis où le picto n'est pas visible mais la référence serait obsolète

**Comment by m-maillot** [comment]
L'outil est déprécié et va bientôt disparaitre.
