### ISSUE TITLE
[outil de contrib] Analyse : permettre d'associer des références juridiques à chaque réponse

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#902]
- Supprimer cdtn-api ? => comprendre ce que ça implique
- Voir si dans un 1er temps on garde cdtn-api et on branche sur redis

**Comment by m-maillot** [comment]
# Supprimer cdtn-api

L'idée est de fusionner le projet cdtn-api au sein de l'admin. Ce projet permet de récupérer les données de legi-data et kali-data afin de les stocker dans une BDD clé-valeur (redis) afin de faciliter la recherche de référence dans l'outil de contribution. Les dépôts kali et legi étant composés de volumineux fichiers json, les performances ne sont pas au rendez vous.

Pour la fusion, l'idée est d'alimenter directement dans notre Hasura les articles de kali et legi via le processus d'ingest. 

### Données LEGI

- [ ] Créer la table de référence legi
- [ ] Mettre à jour la table à partir des données de legi basé sur le script actuel : https://github.com/SocialGouv/cdtn-api/blob/8ce7f4b3e066638e74c28b331b7d4f5a2ed4cf3f/scripts/updateCache.js#L44
- [ ] Développer l'API `GET /code/[id]` qui permet de récupérer l'article à partir de son id (https://github.com/SocialGouv/cdtn-api/blob/8ce7f4b3e066638e74c28b331b7d4f5a2ed4cf3f/src/controllers/Code.js#L15) 
- [ ] Développer l'API `GET /codes?&query=[search]` qui permet de rechercher un article à partir d'une string (https://github.com/SocialGouv/cdtn-api/blob/8ce7f4b3e066638e74c28b331b7d4f5a2ed4cf3f/src/controllers/Code.js#L34)
- [ ] Développer l'API `GET /code/article/LEGIARTI000006901112` qui permet de trouver un article (https://github.com/SocialGouv/cdtn-api/blob/8ce7f4b3e066638e74c28b331b7d4f5a2ed4cf3f/src/controllers/CodeArticle.js#L15)
- [ ] Développer l'API `GET /code/articles?codeId=[id]&query=[query]` qui permet de faire une recherche sur les articles (https://github.com/SocialGouv/cdtn-api/blob/8ce7f4b3e066638e74c28b331b7d4f5a2ed4cf3f/src/controllers/CodeArticle.js#L36)

### Données KALI

- [ ] Créer la table de référence kali
- [ ] Mettre à jour la table à partir des données de kali basé sur le script actuel : https://github.com/SocialGouv/cdtn-api/blob/8ce7f4b3e066638e74c28b331b7d4f5a2ed4cf3f/scripts/updateCache.js
- [ ] Développer l'API `GET /agreement/[id]` qui permet de récupérer l'article à partir de son id (https://github.com/SocialGouv/cdtn-api/blob/8ce7f4b3e066638e74c28b331b7d4f5a2ed4cf3f/src/controllers/Agreement.js#L15) 
- [ ] Développer l'API `GET /agreements?&query=[search]` qui permet de rechercher un article à partir d'une string (https://github.com/SocialGouv/cdtn-api/blob/8ce7f4b3e066638e74c28b331b7d4f5a2ed4cf3f/src/controllers/Code.js#L34)
- [ ] Développer l'API `GET /agreement/article/LEGIARTI000006901112` qui permet de trouver un article (https://github.com/SocialGouv/cdtn-api/blob/8ce7f4b3e066638e74c28b331b7d4f5a2ed4cf3f/src/controllers/AgreementArticle.js#L15)
- [ ] Développer l'API `GET /agreement/articles?codeId=[id]&query=[query]` qui permet de faire une recherche sur les articles (https://github.com/SocialGouv/cdtn-api/blob/8ce7f4b3e066638e74c28b331b7d4f5a2ed4cf3f/src/controllers/AgreementArticle.js#L41)

Une fois l'API disponible, on pourra l'utiliser au sein de l'admin pour effectuer les recherches sur les références.

A voir si ce n'est pas plus malin de convertir l'API en requêtes GaphQL. L'API n'est utilisé que pour la contribution et par la suite on pourrait l'utiliser sur l'admin pour aider à la saisie des références.
