### ISSUE TITLE
[Admin] Supprimer les CC locales de la métallurgie

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#974]
Dans le nouveau module de contribution, dans la liste des CC pour chaque question, il faut retirer toutes les CC "locales" de la métallurgie : 

En principe voici la liste : 

<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">
<style>

</style>
</head>

<body>

IDCC | Intitulé
-- | --
54 | METALLURGIE   OETAM REGION PARISIENNE
714 | METALLURGIE   MOSELLE
822 | METALLURGIE SAVOIE
827 | METALLURGIE ARDENNES
828 | METALLURGIE MANCHE
829 | METALLURGIE VAUCLUSE
836 | METALLURGIE HAUTE-SAVOIE
860 | METALLURGIE FINISTERE
863 | METALLURGIE MORBIHAN   ILLE-ET-VILAINE
878 | METALLURGIE RHONE
887 | METALLURGIE EURE
898 | METALLURGIE ALLIER
899 | METALLURGIE MARNE
911 | METALLURGIE SEINE-ET-MARNE
914 | METALLURGIE AIN
920 | METALLURGIE VIENNE
923 | METALLURGIE CHARENTE-MARITIME
930 | METALLURGIE SARTHE
934 | METALLURGIE INDRE
937 | METALLURGIE HAUTE-VIENNE ET   CREUSE
943 | METALLURGIE CALVADOS
948 | METALLURGIE ORNE
965 | METALLURGIE VAR
979 | METALLURGIE LE HAVRE   (SEINE-MARITIME)
984 | METALLURGIE EURE-ET-LOIR
1007 | METALLURGIE THIERS (PUY-DE-DOME)
1059 | METALLURGIE MIDI-PYRENEES
1159 | METALLURGIE NIEVRE
1164 | METALLURGIE SOMME VIMEU
1274 | METALLURGIE CORREZE
1315 | METALLURGIE HAUTE-MARNE ET MEUSE
1353 | METALLURGIE DORDOGNE
1365 | METALLURGIE MEURTHE-ET-MOSELLE
1369 | METALLURGIE LOIRE-ATLANTIQUE
3209 | METALLURGIE DOUBS
1387 | METALLURGIE FLANDRES DOUAISIS
1472 | METALLURGIE PAS-DE-CALAIS
1525 | METALLURGIE DUNKERQUE (NORD)
1560 | METALLURGIE ALPES-MARITIMES
1564 | METALLURGIE SAONE-ET-LOIRE
1572 | METALLURGIE CHARENTE
1576 | METALLURGIE CHER
1577 | METALLURGIE HERAULT AUDE   PYRENEES-ORIENTALES
1578 | METALLURGIE LOIRE ET   ARRONDISSEMENT D'YSSINGEAUX
1592 | METALLURGIE VALENCIENNOIS   CAMBRESIS (NORD)
1604 | METALLURGIE ROUEN DIEPPE   (SEINE-MARITIME)
1626 | METALLURGIE HAUTES-PYRENEES
1627 | METALLURGIE CLERMONT-FERRAND   PUY-DE-DOME
1628 | METALLURGIE DEUX-SEVRES
1634 | METALLURGIE COTES-D'ARMOR
1635 | METALLURGIE GIRONDE LANDES
1732 | METALLURGIE YONNE
3231 | METALLURGIE JURA
1813 | METALLURGIE MAUBEUGE (NORD)
1867 | METALLURGIE DROME-ARDECHE
1885 | METALLURGIE COTE-D'OR
1902 | METALLURGIE MAINE-ET-LOIRE
1912 | METALLURGIE HAUT-RHIN
1960 | METALLURGIE LOT-ET-GARONNE
1966 | METALLURGIE LOIRET
1967 | METALLURGIE BAS-RHIN
2003 | METALLURGIE VOSGES
2126 | METALLURGIE GARD ET LOZERE
2221 | METALLURGIE ISERE HAUTES-ALPES   (MENSUELS)
2266 | METALLURGIE MAYENNE
2294 | METALLURGIE AUBE
2489 | METALLURGIE VENDEE
2542 | METALLURGIE AISNE
2579 | METALLURGIE LOIR-ET-CHER
2615 | METALLURGIE PYRENEES-ATLANTIQUES   ET DU SEIGNANX
2630 | METALLURGIE BOUCHES-DU-RHONE   ALPES-HAUTE-PROVENCE
2700 | METALLURGIE DE L'OISE
2755 | METALLURGIE BELFORT MONTBELIARD
2980 | METALLURGIE SOMME
2992 | METALLURGIE INDRE-ET-LOIRE
3053 | METALLURGIE HAUTE-SAONE

</body>

</html>

**Comment by Viczei** [comment]
Script pour la suppression:
`with children_ids as (
    select value->>'idcc' as idcc
    from json_array_elements('[{"kali_id":"KALICONT000025393730","idcc":1635},{"kali_id":"KALICONT000019938657","idcc":2542},{"kali_id":"KALICONT000023278100","idcc":2579},{"kali_id":"KALICONT000005635179","idcc":1001},{"kali_id":"KALICONT000005635149","idcc":54},{"kali_id":"KALICONT000005635842-827","idcc":827},{"kali_id":"KALICONT000005635842-828","idcc":828},{"kali_id":"KALICONT000005635842-829","idcc":829},{"kali_id":"KALICONT000005635842-878","idcc":878},{"kali_id":"KALICONT000005635842-836","idcc":836},{"kali_id":"KALICONT000005635842-914","idcc":914},{"kali_id":"KALICONT000005635842-898","idcc":898},{"kali_id":"KALICONT000005635842-920","idcc":920},{"kali_id":"KALICONT000005635842-1007","idcc":1007},{"kali_id":"KALICONT000005635842-863","idcc":863},{"kali_id":"KALICONT000005635842-934","idcc":934},{"kali_id":"KALICONT000005635842-887","idcc":887},{"kali_id":"KALICONT000005635842-984","idcc":984},{"kali_id":"KALICONT000005635842-899","idcc":899},{"kali_id":"KALICONT000005635842-911","idcc":911},{"kali_id":"KALICONT000005635842-937","idcc":937},{"kali_id":"KALICONT000005635842-923","idcc":923},{"kali_id":"KALICONT000005635842-943","idcc":943},{"kali_id":"KALICONT000005635842-979","idcc":979},{"kali_id":"KALICONT000005635842-948","idcc":948},{"kali_id":"KALICONT000005635842-1560","idcc":1560},{"kali_id":"KALICONT000005635842-965","idcc":965},{"kali_id":"KALICONT000005635842-930","idcc":930},{"kali_id":"KALICONT000005635842-1387","idcc":1387},{"kali_id":"KALICONT000005635842-1164","idcc":1164},{"kali_id":"KALICONT000005635842-1274","idcc":1274},{"kali_id":"KALICONT000005635842-1353","idcc":1353},{"kali_id":"KALICONT000005635842-1369","idcc":1369},{"kali_id":"KALICONT000005635842-1525","idcc":1525},{"kali_id":"KALICONT000005635842-1592","idcc":1592},{"kali_id":"KALICONT000005635842-1472","idcc":1472},{"kali_id":"KALICONT000005635842-1572","idcc":1572},{"kali_id":"KALICONT000005635842-1578","idcc":1578},{"kali_id":"KALICONT000005635842-1577","idcc":1577},{"kali_id":"KALICONT000005635842-1634","idcc":1634},{"kali_id":"KALICONT000005635842-1867","idcc":1867},{"kali_id":"KALICONT000005635842-1885","idcc":1885},{"kali_id":"KALICONT000005635842-1627","idcc":1627},{"kali_id":"KALICONT000005635842-1732","idcc":1732},{"kali_id":"KALICONT000005635842-3231","idcc":3231},{"kali_id":"KALICONT000005635842-1813","idcc":1813},{"kali_id":"KALICONT000005635842-1628","idcc":1628},{"kali_id":"KALICONT000005635842-1902","idcc":1902},{"kali_id":"KALICONT000005635842-2221","idcc":2221},{"kali_id":"KALICONT000005635842-1966","idcc":1966},{"kali_id":"KALICONT000005635842-1967","idcc":1967},{"kali_id":"KALICONT000005635842-1912","idcc":1912},{"kali_id":"KALICONT000005635842-2003","idcc":2003},{"kali_id":"KALICONT000005635842-2126","idcc":2126},{"kali_id":"KALICONT000005635842-2615","idcc":2615},{"kali_id":"KALICONT000005635842-2489","idcc":2489},{"kali_id":"KALICONT000005635842-2266","idcc":2266},{"kali_id":"KALICONT000005635842-3053","idcc":3053},{"kali_id":"KALICONT000005635842-2700","idcc":2700},{"kali_id":"KALICONT000005635842-2980","idcc":2980},{"kali_id":"KALICONT000005635842-822","idcc":822},{"kali_id":"KALICONT000005635842-2755","idcc":2755},{"kali_id":"KALICONT000005635842-1564","idcc":1564},{"kali_id":"KALICONT000005635842-2630","idcc":2630},{"kali_id":"KALICONT000005635842-3209","idcc":3209},{"kali_id":"KALICONT000005635842-1159","idcc":1159},{"kali_id":"KALICONT000005635842-860","idcc":860},{"kali_id":"KALICONT000005635842-2992","idcc":2992},{"kali_id":"KALICONT000005635842-1576","idcc":1576},{"kali_id":"KALICONT000005635842-714","idcc":714},{"kali_id":"KALICONT000005635842-1315","idcc":1315},{"kali_id":"KALICONT000005635842-1365","idcc":1365},{"kali_id":"KALICONT000005635842-2294","idcc":2294},{"kali_id":"KALICONT000005635842-1059","idcc":1059},{"kali_id":"KALICONT000005635842-1960","idcc":1960},{"kali_id":"KALICONT000005635842-1604","idcc":1604},{"kali_id":"KALICONT000005635842-1626","idcc":1626}]')
)
delete from public.agreements
where id = any(select idcc from children_ids)`

**Comment by m-maillot** [comment]
Je ne pense pas que la requête soit correcte. Il me reste des CCs départementale.

Pour pour il faut supprimer les CCs qui sont retournées par cette requête : 
```sql
SELECT * FROM contrib.agreements WHERE parent_id IS NOT NULL;
```

Il devrait ne rester que 51 CCs dont voici la liste (c'est la liste des CCs avec une réponse dans l'ancien outil de contrib) : 
```
0843
2111
1596
2609
1979
2941
1527
0675
0016
1486
1483
1606
2395
1505
1351
1996
2120
1043
0650
3043
1147
1702
0787
0176
1672
2420
2216
1404
1480
2148
0086
3127
1090
0044
0029
1501
2614
2511
0292
0573
2596
1266
0275
2264
1517
0413
3239
2098
1516
1518
1597
```

**Comment by m-maillot** [comment]
Voici la liste des CCs des métallurgies dans l'ancien outil de contrib : 
```
0827,"Convention collective départementale des industries métallurgiques, mécaniques et connexes des Ardennes"
0828,"Convention collective départementale des industries métallurgiques, mécaniques, connexes et similaires de la Manche"
0829,Convention collective départementale des industries métallurgiques et des industries connexes du Vaucluse
0878,Convention collective départementale des mensuels des industries métallurgiques du Rhône
0836,"Convention collective départementale des industries métallurgiques, mécaniques, électriques, connexes et similaires de la Haute-Savoie"
0914,Convention collective départementale des mensuels des industries métallurgiques de l'Ain
0898,"Convention collective départementale des industries métallurgiques, mécaniques, électriques, connexes et similaires de l'Allier"
0920,Convention collective départementale des industries métallurgiques électriques et connexes de la Vienne
1007,"Convention collective locale d'arrondissement des industries métallurgiques, mécaniques, connexes et similaires de la région de Thiers (Puy-de-Dôme)"
0863,Convention collective régionale des industries métallurgiques et connexes d'Ille-et-Vilaine et du Morbihan
0934,Convention collective départementale des industries métallurgiques mécaniques connexes et similaires de l'Indre
0887,"Convention collective départementale des industries métallurgiques, mécaniques, électriques et connexes de l'Eure"
0984,"Convention collective départementale des industries métallurgiques, mécaniques et connexes d'Eure-et-Loir"
0899,"Convention collective départementale des industries métallurgiques, mécaniques et connexes de la Marne"
0911,"Convention collective départementale des industries métallurgiques, mécaniques, électriques, connexes et similaires de Seine-et-Marne"
0937,Convention collective régionale des industries métallurgiques mécaniques et connexes de la Haute-Vienne et de la Creuse
0923,Convention collective départementale de la métallurgie de la Charente-Maritime
0943,Convention collective départementale des industries métallurgiques mécaniques et connexes du Calvados
0979,Convention collective locale des industries métallurgiques de l'arrondissement du Havre (Seine-Maritime)
0948,"Convention collective départementale des industries métallurgiques, mécaniques et connexes de l'Orne"
1560,"Convention collective départementale des industries métallurgiques, électriques et connexes des AlpesMaritimes"
0965,Convention collective départementale des industries métallurgiques et connexes du département du Var
0930,Convention collective départementale de la métallurgie et des industries connexes de la Sarthe
1387,Convention collective locale des mensuels des industries métallurgiques des Flandres
1164,Convention collective locale des industries métallurgiques et annexes de la région de Vimeu (Somme)
1274,Convention collective départementale des industries métallurgiques de la Corrèze
1353,Convention collective départementale des industries métallurgiques et connexes de la Dordogne
1369,"Convention collective départementale des industries métallurgiques, électriques, électroniques et connexes de Loire-Atlantique"
1525,Convention collective locale de la métallurgie de la région dunkerquoise
1592,Convention collective locale de la métallurgie du Valenciennois et du Cambrésis
1472,Convention collective départementale des industries métallurgiques du Pas-de-Calais
1572,Convention collective départementale de la métallurgie de la Charente
1578,Convention collective départementale de la métallurgie de la Loire et de l'arrondissement d'Yssingeaux
1577,"Convention collective régionale des industries métallurgiques, électroniques et connexes de l'Hérault, de l'Aude et des Pyrénées-Orientales"
1634,Convention collective départementale de la métallurgie des Côtes-d'Armor
1867,Convention collective régionale de la métallurgie de la Drôme-Ardèche
1885,"Convention collective départementale des industries métallurgiques, mécaniques, électriques et connexes du département de la Côte-d'Or"
1627,Convention collective départementale du travail des industries de la métallurgie et des constructions mécaniques de Clermont-Ferrand et du Puy-de-Dôme
1732,"Convention collective départementale des industries métallurgiques, mécaniques, électriques et connexes de l'Yonne"
1813,Convention collective locale de travail des industries de la transformation des métaux de la région de Maubeuge
1635,"Convention collective régionale des industries métallurgiques, mécaniques et connexes de la Gironde et des Landes"
1628,Convention collective départementale de la métallurgie des Deux-Sèvres
1902,"Convention collective départementale des industries métallurgiques, mécaniques, électriques, électroniques connexes et similaires du Maine-et-Loire"
2221,Convention collective régionale des mensuels des industries des métaux de l'Isère et des Hautes-Alpes
1966,Convention collective départementale des industries métallurgiques du Loiret
1967,Convention collective départementale de l'industrie des métaux du Bas-Rhin
1912,Convention collective départementale des industries de la métallurgie du Haut-Rhin
2003,"Convention collective départementale des industries métallurgiques, électriques, électroniques et connexes du département des Vosges"
2126,Convention collective régionale de la métallurgie du Gard et de la Lozère
2542,"Convention collective départementale des industries métallurgiques, mécaniques et connexes de l'Aisne"
2615,Convention collective régionale de la métallurgie des Pyrénées-Atlantiques et du Seignanx
2266,"Convention collective départementale des industries métallurgiques, mécaniques, électriques, connexes et similaires de la Mayenne"
3053,Convention collective départementale des industries de la métallurgie de Haute-Saône
2700,Convention collective départementale de la métallurgie de l'Oise
2980,Convention collective départementale de la métallurgie de la Somme
1001,Convention collective nationale des médecins spécialistes qualifiés au regard du conseil de l'ordre travaillant dans des établissements et services pour personnes inadaptées et handicapées
0822,Convention collective départementale applicable aux mensuels de la métallurgie de la Savoie
2755,Convention collective départementale des industries de la métallurgie de Belfort/Montbéliard
1564,Convention collective départementale des industries de la métallurgie de Saône-et-Loire
2630,Convention collective régionale des industries métallurgiques des Bouches-du-Rhône et Alpes-de-HauteProvence
1159,Convention collective départementale de la métallurgie de la Nièvre
0860,Convention collective départementale de la métallurgie et des industries connexes du Finistère
2579,Conventions collectives départementales des industries et métiers de la métallurgie du Loir-et-Cher
2992,"Convention collective départementale des industries métallurgiques, mécaniques, électriques, connexes et similaires d'Indre-et Loire"
1576,"Convention collective départementale de travail des industries métallurgiques, mécaniques, électriques, électroniques, connexes et similaires du département du Cher"
0714,Convention collective départementale des industries du travail des métaux de la Moselle (métallurgie)
1315,"Convention collective régionale des industries métallurgiques, mécaniques et connexes de la Haute-Marne et de la Meuse"
1365,Convention collective départementale de travail des industries de transformation des métaux de Meurthe-et-Moselle (métallurgie)
2294,Convention collective départementale des industries et métiers de la métallurgie de l'Aube
1059,"Convention collective régionale des industries métallurgiques, électriques, électroniques et connexes de MidiPyrénées (Ariège, Aveyron, Gers, Haute-Garonne, Tarn, Tarn-et-Garonne, Lot, Aude convention du 1er avril 1980)"
1960,"Convention collective départementale des industries métallurgiques, mécaniques et connexes du Lot-et-Garonne"
1604,Convention collective métallurgie Rouen Dieppe (Seine-Maritime)
1626,"Convention collective départementale des industries métallurgiques, mécaniques, électriques, électrocéramiques et connexes des Hautes-Pyrénées"
2489,Convention collective départementale des industries métallurgiques et assimilées de la Vendée
0054,"Convention collective régionale des ouvriers, employés, techniciens et agents de maîtrise des industries métallurgiques, mécaniques et connexes de la région parisienne"
3209,"Convention collective Métallurgie Doubs ( Industries Mécaniques, Microtechniques et connexes du département du Doubs)"
3231,"Convention collective départementale des industries métallurgiques, mécaniques, similaires et connexes du Jura du 11 janvier 2019"
```
