### ISSUE TITLE
[admin] Création des messages "textes applicables" pour les contrib

### ISSUE THREAD

**Issue by romain-b13** [SocialGouv/cdtn-admin#996]
Il faut finaliser la partie ci-dessous (cf image). 

Dans le menu déroulant on doit avoir :
- Message bloc 3
- Message bloc 1 et 2
- Message domaine exclusif à la branche
- Message Q°X
- Message Q°Y
- Message Q°Z

Il faudra également qu'on puisse définir 2 messages différents quand c'est la contrib générique qui sera affichée (ces messages seront différents aussi selon le bloc sélectionné) : 
- 1 message pour les cas suivants : l'usager sélectionne une CC non traitée, sélectionne une CC traitée sur le CDTN mais dont la réponse à cette question a été dépubliée, l'usager ne renseigne pas sa CC
- 1 message pour le cas suivant : la CC ne prévoit rien sur ce sujet (ou renvoie explicitement aux dispositions du code du travail)

### En résumé

Pour chaque question définir le bloc/type de message concerné et à ce bloc doit être rattaché “en back” 3 messages : 

- 1 msg quand une CC traitée est sélectionnée
- 1 msg quand c’est la générique qui est affichée (sélection d’une CC non traitée ou d’une CC dont on ne publie pas la rép à cette question ou l’usager ne souhaite pas renseigner de CC)
- 1 msg quand c’est la générique qui est affichée car la CC traitée sélectionné ne prévoit rien

Dans l’admin au niveau de chaque question le menu déroulant contiendra X options :

- Message bloc 3
- Message (bloc 1 et 2) Q°A 
- Message (bloc 1 et 2) Q°B
- Message domaine exclusif à la branche
- Message Q°X (ex : si la question mélange plusieurs blocs)
- Message Q°Y (ex : si la question mélange plusieurs blocs)
-

**Comment by carolineBda** [comment]
A vérifier si ce qu'on a implémenté est toujours valide
